In [1]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones(10) ** 5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.rand(1)

array([0.65208318])

In [12]:
np.random.randn(25)

array([ 0.09084807,  1.09163751, -1.25860747,  0.37462817, -0.43009642,
        2.44339783,  0.59924486,  0.94671859, -1.27079088,  2.0110289 ,
        1.57349714,  1.14460681, -1.30551386, -0.28530027,  1.01482429,
       -1.53341285, -0.15350496, -0.61902494,  0.13701195, -1.68484536,
       -0.01733121,  1.39620093,  0.48011853,  1.0384787 , -0.73685785])

In [16]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
np.arange(1,26).reshape(5,5)[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [19]:
np.arange(1,26).reshape(5,5)[3,4]

20

In [20]:
np.arange(1,26).reshape(5,5)[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [21]:
np.arange(1,26).reshape(5,5)[4]

array([21, 22, 23, 24, 25])

In [22]:
np.arange(1,26).reshape(5,5)[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
mat = np.arange(1,26).reshape(5,5)

In [24]:
mat.sum()

325

In [28]:
mat.std()

7.211102550927978

In [31]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])